using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Pokemon
{
    public class Ribbons
    {
        #region Constants

        public static int NUM_RIBBONS = 80;

        public static readonly string[] RIBBON_NAMES = new string[]
        {
            "Cool Ribbon",
            "Cool Ribbon Super",
            "Cool Ribbon Hyper",
            "Cool Ribbon Master",
            "Beauty Ribbon",
            "Beauty Ribbon Super",
            "Beauty Ribbon Hyper",
            "Beauty Ribbon Master",
            "Cute Ribbon",
            "Cute Ribbon Super",
            "Cute Ribbon Hyper",
            "Cute Ribbon Master",
            "Smart Ribbon",
            "Smart Ribbon Super",
            "Smart Ribbon Hyper",
            "Smart Ribbon Master",
            "Tough Ribbon",
            "Tough Ribbon Super",
            "Tough Ribbon Hyper",
            "Tough Ribbon Master",
            "Cool Ribbon",
            "Cool Ribbon Great",
            "Cool Ribbon Ultra",
            "Cool Ribbon Master",
            "Beauty Ribbon",
            "Beauty Ribbon Great",
            "Beauty Ribbon Ultra",
            "Beauty Ribbon Master",
            "Cute Ribbon",
            "Cute Ribbon Great",
            "Cute Ribbon Ultra",
            "Cute Ribbon Master",
            "Smart Ribbon",
            "Smart Ribbon Great",
            "Smart Ribbon Ultra",
            "Smart Ribbon Master",
            "Tough Ribbon",
            "Tough Ribbon Great",
            "Tough Ribbon Ultra",
            "Tough Ribbon Master",
            "Winning Ribbon",
            "Victory Ribbon",
            "Ability Ribbon",
            "Great Ability Ribbon",
            "Double Ability Ribbon",
            "Multi Ability Ribbon",
            "Pair Ability Ribbon",
            "World Ability Ribbon",
            "Champion Ribbon",
            "Sinnoh Champ Ribbon",
            "Record Ribbon",
            "Event Ribbon",
            "Legend Ribbon",
            "Gorgeous Ribbon",
            "Royal Ribbon",
            "Gorgeous Royal Ribbon",
            "Alert Ribbon",
            "Shock Ribbon",
            "Downcast Ribbon",
            "Careless Ribbon",
            "Relax Ribbon",
            "Snooze Ribbon",
            "Smile Ribbon",
            "Footprint Ribbon",
            "Artist Ribbon",
            "Effort Ribbon",
            "Birthday Ribbon",
            "Special Ribbon",
            "Classic Ribbon",
            "Premier Ribbon",
            "Souvenir Ribbon",
            "Wishing Ribbon",
            "National Ribbon",
            "Country Ribbon",
            "Battle Champion Ribbon",
            "Regional Champion Ribbon",
            "Earth Ribbon",
            "World Ribbon",
            "National Champion Ribbon",
            "World Champion Ribbon"
        };

        public static readonly string[] RIBBON_DESCRIPTIONS = new string[]
        {
            "Hoenn Cool Contest Normal Rank winner!",
            "Hoenn Cool Contest Super Rank winner!",
            "Hoenn Cool Contest Hyper Rank winner!",
            "Hoenn Cool Contest Master Rank winner!",
            "Hoenn Beauty Contest Normal Rank winner!",
            "Hoenn Beauty Contest Super Rank winner!",
            "Hoenn Beauty Contest Hyper Rank winner!",
            "Hoenn Beauty Contest Master Rank winner!",
            "Hoenn Cute Contest Normal Rank winner!",
            "Hoenn Cute Contest Super Rank winner!",
            "Hoenn Cute Contest Hyper Rank winner!",
            "Hoenn Cute Contest Master Rank winner!",
            "Hoenn Smart Contest Normal Rank winner!",
            "Hoenn Smart Contest Super Rank winner!",
            "Hoenn Smart Contest Hyper Rank winner!",
            "Hoenn Smart Contest Master Rank winner!",
            "Hoenn Tough Contest Normal Rank winner!",
            "Hoenn Tough Contest Super Rank winner!",
            "Hoenn Tough Contest Hyper Rank winner!",
            "Hoenn Tough Contest Master Rank winner!",
            "Super Contest Cool Category Normal Rank winner!",
            "Super Contest Cool Category Great Rank winner!",
            "Super Contest Cool Category Ultra Rank winner!",
            "Super Contest Cool Category Master Rank winner!",
            "Super Contest Beauty Category Normal Rank winner!",
            "Super Contest Beauty Category Great Rank winner!",
            "Super Contest Beauty Category Ultra Rank winner!",
            "Super Contest Beauty Category Master Rank winner!",
            "Super Contest Cute Category Normal Rank winner!",
            "Super Contest Cute Category Great Rank winner!",
            "Super Contest Cute Category Ultra Rank winner!",
            "Super Contest Cute Category Master Rank winner!",
            "Super Contest Smart Category Normal Rank winner!",
            "Super Contest Smart Category Great Rank winner!",
            "Super Contest Smart Category Ultra Rank winner!",
            "Super Contest Smart Category Master Rank winner!",
            "Super Contest Tough Category Normal Rank winner!",
            "Super Contest Tough Category Great Rank winner!",
            "Super Contest Tough Category Ultra Rank winner!",
            "Super Contest Tough Category Master Rank winner!",
            "Ribbon awarded for clearing Hoenn's Battle Tower's Lv. 50 challenge.",
            "Ribbon awarded for clearing Hoenn's Battle Tower's Lv. 100 challenge.",
            "A Ribbon awarded for defeating the Tower Tycoon at the Battle Tower.",
            "A Ribbon awarded for defeating the Tower Tycoon at the Battle Tower.",
            "A Ribbon awarded for completing the Battle Tower Double challenge.",
            "A Ribbon awarded for completing the Battle Tower Multi challenge.",
            "A Ribbon awarded for completing the Battle Tower Link Multi challenge.",
            "A Ribbon awarded for completing the Wi-Fi Battle Tower challenge.",
            "Ribbon for clearing the Pokémon League and entering the Hall of Fame in another region. ",
            "Ribbon awarded for beating the Sinnoh Champion and entering the Hall of Fame.",
            "A Ribbon awarded for setting an incredible record.",
            "Pokémon Event Participation Ribbon.",
            "A Ribbon awarded for setting a legendary record.",
            "An extraordinarily gorgeous and extravagant Ribbon.",
            "An incredibly regal Ribbon with an air of nobility.",
            "A gorgeous and regal Ribbon that is the peak of fabulous.",
            "A Ribbon for recalling an invigorating event that created life energy.",
            "A Ribbon for recalling a thrilling event that made life more exciting.",
            "A Ribbon for recalling feelings of sadness that added spice to life.",
            "A Ribbon for recalling a careless error that helped steer life decisions.",
            "A Ribbon for recalling a refreshing event that added sparkle to life.",
            "A Ribbon for recalling a deep slumber that made life soothing.",
            "A Ribbon for recalling that smiles enrich the quality of life.",
            "A Ribbon awarded to a Pokémon deemed to have a top-quality footprint.",
            "Ribbon awarded for being chosen as a super sketch model in Hoenn.",
            "Ribbon awarded for being an exceptionally hard worker.",
            "A Ribbon to celebrate a birthday.",
            "A special Ribbon for a special day.",
            "A Ribbon that proclaims love for Pokémon.",
            "Special Holiday Ribbon.",
            "A Ribbon to cherish a special memory.",
            "A Ribbon said to make your wish come true.",
            "A Ribbon awarded for overcoming all difficult challenges.",
            "Pokémon League Champion Ribbon.",
            "Battle Competition Champion Ribbon.",
            "Pokémon World Championships Regional Champion Ribbon.",
            "A Ribbon awarded for winning 100 matches in a row.",
            "Pokémon League Champion Ribbon.",
            "Pokémon World Championships National Champion Ribbon.",
            "Pokémon World Championships World Champion Ribbon."
        };

        #endregion

    }
}